const zlib=require('node:zlib');
function decodeNbt(encoded){if(!encoded)return[];const b=zlib.gunzipSync(Buffer.from(encoded,'base64'));let o=0;const u8=()=>b.readUInt8(o++),i8=()=>b.readInt8(o++),i16=()=>{const v=b.readInt16BE(o);o+=2;return v},i32=()=>{const v=b.readInt32BE(o);o+=4;return v};const str=()=>{const n=b.readUInt16BE(o);o+=2;const v=b.toString('utf8',o,o+n);o+=n;return v};function read(t){switch(t){case 0:return null;case 1:return i8();case 2:return i16();case 3:return i32();case 4:{const v=Number(b.readBigInt64BE(o));o+=8;return v}case 5:{const v=b.readFloatBE(o);o+=4;return v}case 6:{const v=b.readDoubleBE(o);o+=8;return v}case 7:{const n=i32(),v=b.subarray(o,o+n);o+=n;return v}case 8:return str();case 9:{const type=u8(),n=i32(),a=[];for(let i=0;i<n;i++)a.push(read(type));return a}case 10:{const v={};while(true){const type=u8();if(!type)break;v[str()]=read(type)}return v}case 11:{const n=i32(),a=[];for(let i=0;i<n;i++)a.push(i32());return a}case 12:{const n=i32(),a=[];for(let i=0;i<n;i++){a.push(Number(b.readBigInt64BE(o)));o+=8}return a}default:throw new Error(`Unknown NBT tag ${t}`)}}const type=u8();if(!type)return[];str();const root=read(type);return root.i||root.items||(root.Count?[root]:[])}
function cleanName(value='Unknown item'){return String(value).replace(/§[0-9a-fk-or]/gi,'')}
function titleCase(value){return String(value).toLowerCase().split('_').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ')}
function shapeItem(item,group){if(!item||!item.Count)return null;const extra=item.tag?.ExtraAttributes||{},rawLore=item.tag?.display?.Lore||[],id=extra.id||`MINECRAFT_${item.id}`;return{id,name:cleanName(item.tag?.display?.Name||id.replaceAll('_',' ')),rawName:item.tag?.display?.Name||id.replaceAll('_',' '),count:item.Count,group,icon:`/api/item-texture/${encodeURIComponent(id)}?v=2`,lore:rawLore.map(cleanName),rawLore,reforge:extra.modifier||null,enchantments:extra.enchantments||{},gems:extra.gems||{},stars:Number(extra.upgrade_level||extra.dungeon_item_level||0),attributes:extra.attributes||{},uuid:extra.uuid||null}}
function readContainer(blob,group){try{return decodeNbt(blob?.data).map(item=>shapeItem(item,group))}catch{return[]}}
function readEquipment(member){const items=[];for(const[group,data]of[['Armor',member.inventory?.inv_armor?.data],['Equipment',member.inventory?.equipment_contents?.data]])for(const item of readContainer({data},group)){if(item)items.push(item)}return items}
function readBlob(blob,group){return readContainer(blob,group)[0]||null}
function readLoadouts(member){const data=member.loadout||{},armorOrder=['HELMET','CHESTPLATE','LEGGINGS','BOOTS'],equipmentOrder=['EQUIPMENT_SLOT_1','EQUIPMENT_SLOT_2','EQUIPMENT_SLOT_3','EQUIPMENT_SLOT_4'];const sets=(source,order,group)=>Object.entries(source||{}).filter(([id])=>/^\d+$/.test(id)).map(([id,set])=>({id:Number(id),equipped:Number(source.equipped_set)===Number(id),items:order.map(slot=>readBlob(set[slot],group))})).filter(set=>set.items.some(Boolean));return{armorSets:sets(data.armor,armorOrder,'Armor'),equipmentSets:sets(data.equipment,equipmentOrder,'Equipment'),loadouts:Object.entries(data.loadouts||{}).filter(([id])=>/^\d+$/.test(id)).map(([id,x])=>({id:Number(id),name:cleanName(x.name||`Loadout ${id}`),armorSetId:Number(x.armor_set_id||0),equipmentSetId:Number(x.equipment_set_id||0)}))}}
function readStorage(member){const inventory=member.inventory||{},backpacks=Object.entries(inventory.backpack_contents||{}).map(([id,blob])=>({id,name:`Backpack ${Number(id)+1}`,items:readContainer(blob,'Backpack')})).filter(x=>x.items.some(Boolean)),bags=Object.entries(inventory.bag_contents||{}).map(([id,blob])=>({id,name:titleCase(id),items:readContainer(blob,'Bag')})).filter(x=>x.items.some(Boolean)),sacks=Object.entries(inventory.sacks_counts||member.sacks_counts||{}).filter(([,amount])=>Number(amount)>0).map(([id,amount])=>({id,name:titleCase(id.replace(/:.*$/,'')),count:Number(amount)})).sort((a,b)=>b.count-a.count);return{inventory:readContainer(inventory.inv_contents,'Inventory'),enderChest:readContainer(inventory.ender_chest_contents,'Ender Chest'),personalVault:readContainer(inventory.personal_vault_contents,'Personal Vault'),backpacks,bags,sacks}}
function accessoryStats(member,storage){const data=member.accessory_bag_storage||{},items=storage.bags.find(x=>x.id==='talisman_bag')?.items.filter(Boolean)||[],counts={};for(const item of items)counts[item.id]=(counts[item.id]||0)+1;const tuning=data.tuning?.slot_0||{};return{magicalPower:Number(data.highest_magical_power||0),selectedPower:titleCase(data.selected_power||'None'),unlockedPowers:(data.unlocked_powers||[]).map(titleCase),upgrades:Number(data.bag_upgrades_purchased||0),tuning:Object.entries(tuning).filter(([,v])=>typeof v==='number'&&v!==0).map(([name,value])=>({name:titleCase(name),value})),items,unique:Object.keys(counts).length,duplicates:Object.entries(counts).filter(([,v])=>v>1).map(([id,count])=>({id,name:items.find(x=>x.id===id)?.name||titleCase(id),count}))}}
module.exports={cleanName,titleCase,readEquipment,readLoadouts,readStorage,accessoryStats};
